name: CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTIONSTRING: mongodb://localhost:27017/epdv-local
      AUTH_KEY: auth-key
      AUTH_TOKENEXPIRATION: 86400
      STRIPE_API_KEY: sk_test_51IwoaUI3DLjCBNrB1UQ8i6OOZcHDPm5OAHaujqPklWjhFe9sZgP5V6SIOGCl8pgwTsGwpq3E9GZsVaGKrwHxBIZt00TARUtyjM
      STRIPE_API_VERSION: 2020-03-02

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: [4.4]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.1.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run all tests
        run: npm run test
